# Generated by Django 5.1.7 on 2025-03-21 12:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Тема")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Введите описание",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Создана"),
                            ("work", "В работе"),
                            ("complete", "Выполнена"),
                            ("close", "Закрыта"),
                        ],
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала выполнения"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения выполнения"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                        ],
                        max_length=8,
                        null=True,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="task",
                        verbose_name="Скриншот/фото проблемы",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="task", verbose_name="Файлы"
                    ),
                ),
                (
                    "commentary",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "wishes",
                    models.BooleanField(
                        default=False,
                        help_text="Утвердить обращение",
                        verbose_name="Утверждено",
                    ),
                ),
                (
                    "anydesk",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите номер AnyDesk для подключения. Загрузить AnyDesk можно внизу страницы.",
                        null=True,
                        verbose_name="AnyDesk",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("access", "Предоставить/отключить доступ"),
                            ("1c", "1С"),
                            ("network", "Сеть и доступность"),
                            ("directum", "Directum"),
                            ("mail", "Вопросы по почте"),
                            ("equipment", "Оборудование"),
                            ("software", "Установка ПО"),
                            ("other", "Другое"),
                            ("auto_mods", "Автоматизация и доработки"),
                        ],
                        max_length=50,
                        verbose_name="Категория заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("-created_at",),
                "permissions": [("can_edit_status_task", "Can edit status task")],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к задаче",
                "verbose_name_plural": "Комментарии к задачам",
                "ordering": ("created_at",),
            },
        ),
    ]
