# Generated by Django 5.1.7 on 2025-03-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите согласующего для утверждения заявки (При необходимости)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Согласующий",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="watcher",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите наблюдателей для заявки (При необходимости) Удерживайте “Control“)",
                null=True,
                related_name="watcher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Наблюдатели",
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.task",
                verbose_name="Задача",
            ),
        ),
    ]
